language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - "nightly"

before_install:
- pip install poetry

install:
- poetry install -v

script: py.test  --cov-report term --cov=ga_solver

after_success:
  - bash <(curl -s https://codecov.io/bash)
